apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synthrad-paired-train-data
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi